!======================================================================
! ACCESS-SW-MANAGEMENT — Management VLAN 10 Access Switch
!======================================================================
! Data VLAN : 10 (Management — servers, monitoring, control)
! Isolation  : Only VLAN 10 permitted on trunks — pure separation
!======================================================================

enable secret 5 12345
!
hostname ACCESS-SW-MANAGEMENT
username Hareth secret 5 hareth@2025
ip domain-name telecom.local
spanning-tree mode pvst
spanning-tree extend system-id
!
interface Port-channel1
 description UPLINK to DISTRIBUTION Layer
 switchport trunk native vlan 100
 switchport trunk allowed vlan 10
 switchport mode trunk
!
interface range FastEthernet0/1-22
 description Port for Management Devices
 switchport access vlan 10
 switchport mode access
 spanning-tree portfast
 spanning-tree bpduguard enable
!
interface FastEthernet0/23
 description UPLINK-to-DIST-SW1
 switchport trunk native vlan 100
 switchport trunk allowed vlan 10
 switchport mode trunk
 spanning-tree portfast
 spanning-tree bpduguard enable
!
interface FastEthernet0/24
 description UPLINK-to-DIST-SW2
 switchport trunk native vlan 100
 switchport trunk allowed vlan 10
 switchport mode trunk
 spanning-tree portfast
 spanning-tree bpduguard enable
!
interface GigabitEthernet0/1
 description UPLINK to DISTRIBUTION Layer
 switchport trunk native vlan 100
 switchport trunk allowed vlan 10
 switchport mode trunk
 channel-group 1 mode active
!
interface GigabitEthernet0/2
 description UPLINK to DISTRIBUTION Layer
 switchport trunk native vlan 100
 switchport trunk allowed vlan 10
 switchport mode trunk
 channel-group 1 mode active
!
interface Vlan1
 no ip address
 shutdown
!
interface Vlan10
 ip address 10.10.10.254 255.255.255.0
!
ip default-gateway 10.10.10.1
!
line con 0
 password cisco
 login
line vty 0 4
 password cisco
 login
line vty 5 15
 password cisco
 login
!
end
write memory
