!======================================================================
! ACCESS-SW-IT — IT Department Access Switch
!======================================================================
! Data VLAN : 20 (IT)
! Voice VLAN: 150
! Native    : 100
! Uplinks   : Fa0/23, Fa0/24 → DIST-SW1/DIST-SW2 (separate trunks)
!             Gi0/1, Gi0/2  → EtherChannel Po1 (active)
!======================================================================

enable secret 12345
!
hostname ACCESS-SW-IT
username Hareth secret hareth@2025
ip domain-name telecom.local
spanning-tree mode pvst
spanning-tree extend system-id
!
! --- EtherChannel (uplink bundle) ---
interface Port-channel1
 description UPLINK to DISTRIBUTION Layer
 switchport trunk native vlan 100
 switchport trunk allowed vlan 20,150
 switchport mode trunk
!
! --- Access ports for IT users ---
interface range FastEthernet0/1-22
 description Port for IT Department
 switchport access vlan 20
 switchport mode access
 switchport voice vlan 150
 spanning-tree portfast
 spanning-tree bpduguard enable
!
! --- Dedicated single uplinks ---
interface FastEthernet0/23
 description UPLINK-to-DIST-SW1
 switchport access vlan 20
 switchport trunk native vlan 100
 switchport mode trunk
 switchport voice vlan 150
 spanning-tree portfast
 spanning-tree bpduguard enable
!
interface FastEthernet0/24
 description UPLINK-to-DIST-SW2
 switchport access vlan 20
 switchport trunk native vlan 100
 switchport mode trunk
 switchport voice vlan 150
 spanning-tree portfast
 spanning-tree bpduguard enable
!
! --- EtherChannel members ---
interface GigabitEthernet0/1
 description UPLINK to DISTRIBUTION Layer
 switchport trunk native vlan 100
 switchport trunk allowed vlan 20,150
 switchport mode trunk
 channel-group 1 mode active
!
interface GigabitEthernet0/2
 description UPLINK to DISTRIBUTION Layer
 switchport trunk native vlan 100
 switchport trunk allowed vlan 20,150
 switchport mode trunk
 channel-group 1 mode active
!
! --- Disable default VLAN1 mgmt ---
interface Vlan1
 no ip address
 shutdown
!
interface Vlan20
 ip address 10.10.20.254 255.255.255.0
!
ip default-gateway 10.10.20.1
!
line con 0
 password cisco
 login
line vty 0 4
 password cisco
 login
line vty 5 15
 password cisco
 login
!
end
write memory
